server:
  port: 0

stats-server:
  url: ${CLIENT_URL:http://localhost:9090}

spring:
  application:
    name: main-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Moscow
    locale: ru_RU

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/main-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      zalando:
        logbook: trace

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000